import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Navigation from '@/components/Navigation';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// 타이틀을 템플릿으로 지정하고 각 컴포넌트마다 지정한 타이틀 값을 '%s'에 대입하여 보여줌
export const metadata: Metadata = {
  title: {
    template: '%s | Next.js 14 Movies',
    default: 'Loading...'
  },
  description: 'Generated by Next.js 14'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navigation />
        <main className='flex min-h-screen flex-col items-center justify-between p-24'>{children}</main>
      </body>
    </html>
  );
}
